### ISSUE TITLE
Modularize the jiva CI integration test script (start_init_test.sh)

### ISSUE THREAD

**Issue by ksatchit** [openebs/jiva#134]
The jiva CI integration tests are currently placed in a single bash script that is executed as part of the travis build process. This script needs to be modularized (separate out the individual test functions) to aid easier management and adhere to BCH standards. Increased comments/test-descriptions to specify test intent also will help. 

https://github.com/openebs/jiva/blob/master/ci/start_init_test.sh

**Comment by kmjayadeep** [comment]
Also we should avoid using sleeps and long loops in test scripts. Tests are taking a long time to complete due to this. We should come up with some better approach.

I think it would be a better idea to write the results of each test cases (whether it is passing or not) and errors if failed, to separate temporary file. Now there are too much logs on console output which makes it hard to debug.

**Comment by ksatchit** [comment]
cc: @payes @utkarshmani1997

**Comment by utkarshmani1997** [comment]
@kmjayadeep the tests are not taking too much time. It's hardly taking ~20 minutes rather building everything from scratch in Docker env is taking time. It takes approximately ~15 minutes to build and containerize the whole module because it downloads various dependencies and install into the container env.
Anyway we are open for any changes and suggestions and would always be looking for the improvements.

**Comment by utkarshmani1997** [comment]
@MagnumOpus21 can you please share your thoughts on modularizing the scripts ?

**Comment by MagnumOpus21** [comment]
@utkarshmani1997 I was just asking suggestions so I could work on this. :sweat:

**Comment by kmjayadeep** [comment]
@utkarshmani1997 
How about a structure like this?
- start_init_test.sh --> entry point
- lib/ --> reusable functions to start containers, stop containers etc.
- tests/ --> individual test cases
  - test_single_replica_start.sh
  - test_two_replica_start.sh

**Comment by utkarshmani1997** [comment]
@kmjayadeep sounds good. 
cc: @MagnumOpus21

**Comment by MagnumOpus21** [comment]
@utkarshmani1997 I will try to finish this on the weekend, if that's okay with you.

**Comment by MagnumOpus21** [comment]
If you want to go ahead with the work do go ahead. I have some work till the middle of next week.

**Comment by kmjayadeep** [comment]
working in this

**Comment by kmova** [comment]
Split the tests into multiple files. 
https://github.com/openebs/jiva/tree/master/ci

Further modularization can be taken in the upcoming releases.
